In [1]:
# Instala el driver de PyMongo con soporte para registros SRV, necesario para conectarse a MongoDB Atlas.
!python -m pip install "pymongo[srv]"

Requirement already satisfied: pymongo[srv] in /usr/local/python/3.12.1/lib/python3.12/site-packages (4.13.2)
WARNING: pymongo 4.13.2 does not provide the extra 'srv'
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pymongo[srv]) (2.7.0)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python -m pip install --upgrade pip

In [2]:
# Importa la clase MongoClient y ServerApi del módulo pymongo.
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

# Define la URI de conexión para MongoDB Atlas, incluyendo credenciales y detalles del clúster.
uri = "mongodb+srv://cesarcp:1234@default.pnri1kk.mongodb.net/?retryWrites=true&w=majority&appName=default"
  
# Crea una nueva instancia del cliente de MongoDB y se conecta al servidor.
client = MongoClient(uri, server_api=ServerApi('1'))

# Utiliza un bloque try-except para manejar posibles errores de conexión.
try:
    # Envía un comando 'ping' al servidor para verificar la conexión.
    client.admin.command('ping')
    # Imprime un mensaje de éxito si la conexión es exitosa.
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    # Si ocurre un error, imprime el mensaje de la excepción.
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [4]:
import pandas as pd

In [ ]:
# Accede a la base de datos 'sample_airbnb' del cliente.
dbname = client['sample_airbnb']
# Accede a la colección 'listingsAndReviews' dentro de la base de datos.
collection_name = dbname['listingsAndReviews']

# Realiza una consulta para traer todos los documentos de la colección.
# El resultado es un cursor de PyMongo, no un DataFrame de pandas.
listingsAndReviews_df = collection_name.find({})
# listingsAndReviews_cursor = collection_name.find({})

# Muestra el objeto del cursor, confirmando que es un 'Cursor' de PyMongo.
# Un cursor es un iterador que permite recorrer los resultados de la consulta.
# No se puede imprimir directamente como un DataFrame completo.
listingsAndReviews_df

In [5]:
# Accede a la base de datos 'sample_airbnb' del cliente.
dbname = client['sample_airbnb']
# Accede a la colección 'listingsAndReviews' dentro de la base de datos.
collection_name = dbname['listingsAndReviews']

# Realiza una consulta para obtener todos los documentos de la colección y los almacena en un cursor.
listingsAndReviews_cursor = collection_name.find({})

# Convierte el cursor de MongoDB a un DataFrame de pandas.
listingsAndReviews_df = pd.DataFrame(listingsAndReviews_cursor)
# Muestra las primeras 5 filas del DataFrame para verificar los datos.
listingsAndReviews_df.head()

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,guests_included,images,host,address,availability,review_scores,reviews,weekly_price,monthly_price,reviews_per_month
0,10006546,https://www.airbnb.com/rooms/10006546,Ribeira Charming Duplex,Fantastic duplex apartment with three bedrooms...,Privileged views of the Douro River and Ribeir...,Fantastic duplex apartment with three bedrooms...,"In the neighborhood of the river, you can find...",Lose yourself in the narrow streets and stairc...,Transport: • Metro station and S. Bento railwa...,We are always available to help guests. The ho...,...,6,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '51399391', 'host_url': 'https://w...","{'street': 'Porto, Porto, Portugal', 'suburb':...","{'availability_30': 28, 'availability_60': 47,...","{'review_scores_accuracy': 9, 'review_scores_c...","[{'_id': '58663741', 'date': 2016-01-03 05:00:...",NaN,NaN,NaN
1,10009999,https://www.airbnb.com/rooms/10009999,Horto flat with small garden,One bedroom + sofa-bed in quiet and bucolic ne...,Lovely one bedroom + sofa-bed in the living ro...,One bedroom + sofa-bed in quiet and bucolic ne...,This charming ground floor flat is located in ...,"There´s a table in the living room now, that d...","Easy access to transport (bus, taxi, car) and ...",,...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '1282196', 'host_url': 'https://ww...","{'street': 'Rio de Janeiro, Rio de Janeiro, Br...","{'availability_30': 0, 'availability_60': 0, '...",{},[],1492.00,4849.00,NaN
2,1001265,https://www.airbnb.com/rooms/1001265,Ocean View Waikiki Marina w/prkg,A short distance from Honolulu's billion dolla...,Great studio located on Ala Moana across the s...,A short distance from Honolulu's billion dolla...,You can breath ocean as well as aloha.,,Honolulu does have a very good air conditioned...,"Pool, hot tub and tennis",...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '5448114', 'host_url': 'https://ww...","{'street': 'Honolulu, HI, United States', 'sub...","{'availability_30': 16, 'availability_60': 46,...","{'review_scores_accuracy': 9, 'review_scores_c...","[{'_id': '4765259', 'date': 2013-05-24 04:00:0...",650.00,2150.00,NaN
3,10021707,https://www.airbnb.com/rooms/10021707,Private Room in Bushwick,Here exists a very cozy room for rent in a sha...,,Here exists a very cozy room for rent in a sha...,,,,,...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '11275734', 'host_url': 'https://w...","{'street': 'Brooklyn, NY, United States', 'sub...","{'availability_30': 0, 'availability_60': 0, '...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '61050713', 'date': 2016-01-31 05:00:...",NaN,NaN,NaN
4,10030955,https://www.airbnb.com/rooms/10030955,Apt Linda Vista Lagoa - Rio,Quarto com vista para a Lagoa Rodrigo de Freit...,,Quarto com vista para a Lagoa Rodrigo de Freit...,,,,,...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '51496939', 'host_url': 'https://w...","{'street': 'Rio de Janeiro, Rio de Janeiro, Br...","{'availability_30': 28, 'availability_60': 58,...",{},[],NaN,NaN,NaN

In [6]:
# Accede a la base de datos 'sample_airbnb' del cliente de MongoDB.
dbname = client['sample_airbnb']
# Accede a la colección 'listingsAndReviews' dentro de la base de datos seleccionada.
collection_name = dbname['listingsAndReviews']

# Busca y recupera documentos de la colección donde el campo 'bedrooms' es 1.
# El resultado de la consulta es un cursor de PyMongo.
listingsAndReviews_cursor = collection_name.find({'bedrooms': 1})

# Convierte el cursor de MongoDB en un DataFrame de pandas.
listingsAndReviews_df = pd.DataFrame(listingsAndReviews_cursor)
# Muestra las primeras cinco filas del DataFrame para verificar el contenido.
listingsAndReviews_df.head()

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,images,host,address,availability,review_scores,reviews,first_review,last_review,security_deposit,reviews_per_month
0,10009999,https://www.airbnb.com/rooms/10009999,Horto flat with small garden,One bedroom + sofa-bed in quiet and bucolic ne...,Lovely one bedroom + sofa-bed in the living ro...,One bedroom + sofa-bed in quiet and bucolic ne...,This charming ground floor flat is located in ...,"There´s a table in the living room now, that d...","Easy access to transport (bus, taxi, car) and ...",,...,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '1282196', 'host_url': 'https://ww...","{'street': 'Rio de Janeiro, Rio de Janeiro, Br...","{'availability_30': 0, 'availability_60': 0, '...",{},[],NaT,NaT,NaN,NaN
1,1001265,https://www.airbnb.com/rooms/1001265,Ocean View Waikiki Marina w/prkg,A short distance from Honolulu's billion dolla...,Great studio located on Ala Moana across the s...,A short distance from Honolulu's billion dolla...,You can breath ocean as well as aloha.,,Honolulu does have a very good air conditioned...,"Pool, hot tub and tennis",...,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '5448114', 'host_url': 'https://ww...","{'street': 'Honolulu, HI, United States', 'sub...","{'availability_30': 16, 'availability_60': 46,...","{'review_scores_accuracy': 9, 'review_scores_c...","[{'_id': '4765259', 'date': 2013-05-24 04:00:0...",2013-05-24 04:00:00,2019-02-07 05:00:00,NaN,NaN
2,10021707,https://www.airbnb.com/rooms/10021707,Private Room in Bushwick,Here exists a very cozy room for rent in a sha...,,Here exists a very cozy room for rent in a sha...,,,,,...,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '11275734', 'host_url': 'https://w...","{'street': 'Brooklyn, NY, United States', 'sub...","{'availability_30': 0, 'availability_60': 0, '...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '61050713', 'date': 2016-01-31 05:00:...",2016-01-31 05:00:00,2016-01-31 05:00:00,NaN,NaN
3,10030955,https://www.airbnb.com/rooms/10030955,Apt Linda Vista Lagoa - Rio,Quarto com vista para a Lagoa Rodrigo de Freit...,,Quarto com vista para a Lagoa Rodrigo de Freit...,,,,,...,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '51496939', 'host_url': 'https://w...","{'street': 'Rio de Janeiro, Rio de Janeiro, Br...","{'availability_30': 28, 'availability_60': 58,...",{},[],NaT,NaT,1000.00,NaN
4,1003530,https://www.airbnb.com/rooms/1003530,New York City - Upper West Side Apt,,"Murphy bed, optional second bedroom available....","Murphy bed, optional second bedroom available....",Great neighborhood - many terrific restaurants...,"My cat, Samantha, are in and out during the su...","Conveniently located near 1, 2, 3, B & C subwa...",New York City!,...,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '454250', 'host_url': 'https://www...","{'street': 'New York, NY, United States', 'sub...","{'availability_30': 0, 'availability_60': 0, '...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '4351675', 'date': 2013-04-29 04:00:0...",2013-04-29 04:00:00,2018-08-12 04:00:00,0.00,NaN

In [ ]:
# Importa la biblioteca 'sqlalchemy' para interactuar con bases de datos SQL.
import sqlalchemy as db

# Crea un motor de base de datos para conectarse a MySQL.
# La cadena de conexión incluye credenciales, host, puerto y el nombre de la base de datos 'retail_db'.
engine = db.create_engine("mysql://root:root@127.0.0.1:3310/retail_db")
# Establece una conexión con la base de datos a través del motor.
conn = engine.connect()

In [ ]:
# Lee los datos de la tabla 'departments' ejecutando una consulta SQL y los carga en un DataFrame de pandas.
departments_df = pd.read_sql_query('select * from departments', conn)
# Muestra las primeras 5 filas del DataFrame para verificar los datos.
departments_df.head()

   department_id department_name
0              2         Fitness
1              3        Footwear
2              4         Apparel
3              5            Golf
4              6        Outdoors

In [ ]:
# Accede a la base de datos 'retail_db' en el cliente de MongoDB.
# La base de datos se creará automáticamente cuando se inserten datos en una colección.
dbname_retail = client['retail_db']
# Accede a la colección 'departments' dentro de la base de datos de MongoDB.
collection_name_departments = dbname_retail['departments']

In [ ]:
# Convierte el DataFrame de pandas a una lista de diccionarios, un formato adecuado para MongoDB.
df_to_dict = departments_df.to_dict('records')
# Inserta múltiples documentos (la lista de diccionarios) en la colección de MongoDB.
# El método devuelve un objeto que contiene los IDs de los documentos insertados.
collection_name_departments.insert_many(df_to_dict)

InsertManyResult([ObjectId('687d2be22a88b02a1c144f69'), ObjectId('687d2be22a88b02a1c144f6a'), ObjectId('687d2be22a88b02a1c144f6b'), ObjectId('687d2be22a88b02a1c144f6c'), ObjectId('687d2be22a88b02a1c144f6d'), ObjectId('687d2be22a88b02a1c144f6e')], acknowledged=True)